MemTest-rails/config/routes.rb
Rails.application.routes.draw do
  resources :interactions
  resources :questions
  resources :associations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "asker", to: "asker#index"
  get "", to: "asker#index"
  post "asker", to: "asker#process_response"
end

MemTest-rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MemTest-rails/app/models/association.rb
class Association < ApplicationRecord
end

MemTest-rails/app/models/interaction.rb
class Interaction < ApplicationRecord
  belongs_to :question
end

MemTest-rails/app/models/question.rb
class Question < ApplicationRecord
end

MemTest-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

MemTest-rails/app/controllers/asker_controller.rb
class AskerController < ApplicationController
  #GET /asker
  def index
    #Generate a Question, and pass it to be displayed.
    @question = Question.create(prompt: "test prompt: choose option 3", choice1: "choice1", choice2: "choice2", choice3: "choice3", choice4: "choice4", correctIndex: 2)
    
  end
  
  #POST /asker
  def process_response
    user_response = params[:index]
    thinking_milis = 0 #TODO
    prompt_time = DateTime.now #TODO
    interaction_record = Interaction.create(question: Question.find(params[:question]), :response => user_response, thinking_milis: thinking_milis, prompt_time: prompt_time)
    #Process the response:
    redirect_to asker_url
  end
end

MemTest-rails/app/controllers/associations_controller.rb
class AssociationsController < ApplicationController
  before_action :set_association, only: [:show, :edit, :update, :destroy]

  # GET /associations
  # GET /associations.json
  def index
    @associations = Association.all
  end

  # GET /associations/1
  # GET /associations/1.json
  def show
  end

  # GET /associations/new
  def new
    @association = Association.new
  end

  # GET /associations/1/edit
  def edit
  end

  # POST /associations
  # POST /associations.json
  def create
    @association = Association.new(association_params)

    respond_to do |format|
      if @association.save
        format.html { redirect_to @association, notice: 'Association was successfully created.' }
        format.json { render :show, status: :created, location: @association }
      else
        format.html { render :new }
        format.json { render json: @association.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /associations/1
  # PATCH/PUT /associations/1.json
  def update
    respond_to do |format|
      if @association.update(association_params)
        format.html { redirect_to @association, notice: 'Association was successfully updated.' }
        format.json { render :show, status: :ok, location: @association }
      else
        format.html { render :edit }
        format.json { render json: @association.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /associations/1
  # DELETE /associations/1.json
  def destroy
    @association.destroy
    respond_to do |format|
      format.html { redirect_to associations_url, notice: 'Association was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_association
      @association = Association.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def association_params
      params.require(:association).permit(:label, :content)
    end
end

MemTest-rails/app/controllers/interactions_controller.rb
class InteractionsController < ApplicationController
  before_action :set_interaction, only: [:show, :edit, :update, :destroy]

  # GET /interactions
  # GET /interactions.json
  def index
    @interactions = Interaction.all
  end

  # GET /interactions/1
  # GET /interactions/1.json
  def show
  end

  # GET /interactions/new
  def new
    @interaction = Interaction.new
  end

  # GET /interactions/1/edit
  def edit
  end

  # POST /interactions
  # POST /interactions.json
  def create
    @interaction = Interaction.new(interaction_params)

    respond_to do |format|
      if @interaction.save
        format.html { redirect_to @interaction, notice: 'Interaction was successfully created.' }
        format.json { render :show, status: :created, location: @interaction }
      else
        format.html { render :new }
        format.json { render json: @interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interactions/1
  # PATCH/PUT /interactions/1.json
  def update
    respond_to do |format|
      if @interaction.update(interaction_params)
        format.html { redirect_to @interaction, notice: 'Interaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @interaction }
      else
        format.html { render :edit }
        format.json { render json: @interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interactions/1
  # DELETE /interactions/1.json
  def destroy
    @interaction.destroy
    respond_to do |format|
      format.html { redirect_to interactions_url, notice: 'Interaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interaction
      @interaction = Interaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interaction_params
      params.require(:interaction).permit(:question_id, :response, :prompt_time, :thinking_milis)
    end
end

MemTest-rails/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:prompt, :choice1, :choice2, :choice3, :choice4, :correctIndex)
    end
end

MemTest-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

MemTest-rails/app/helpers/asker_helper.rb
module AskerHelper
end

MemTest-rails/app/helpers/associations_helper.rb
module AssociationsHelper
end

MemTest-rails/app/helpers/interactions_helper.rb
module InteractionsHelper
end

MemTest-rails/app/helpers/questions_helper.rb
module QuestionsHelper
end

MemTest-rails/app/views/asker/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Asker</h1>

<h2>Prompt: <%= @question.prompt %> </h2>

<% options = [@question.choice1, @question.choice2, @question.choice3, @question.choice4] %>
<% (0...options.length).each do |index| %>
<%= button_to options[index], asker_path(index: index, question: @question.id) %>
<% end %>

MemTest-rails/app/views/associations/_form.html.erb
<%= form_for(association) do |f| %>
  <% if association.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(association.errors.count, "error") %> prohibited this association from being saved:</h2>

      <ul>
      <% association.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %>
    <%= f.text_field :label %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MemTest-rails/app/views/associations/edit.html.erb
<h1>Editing Association</h1>

<%= render 'form', association: @association %>

<%= link_to 'Show', @association %> |
<%= link_to 'Back', associations_path %>

MemTest-rails/app/views/associations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Associations</h1>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @associations.each do |association| %>
      <tr>
        <td><%= association.label %></td>
        <td><%= association.content %></td>
        <td><%= link_to 'Show', association %></td>
        <td><%= link_to 'Edit', edit_association_path(association) %></td>
        <td><%= link_to 'Destroy', association, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Association', new_association_path %>

MemTest-rails/app/views/associations/new.html.erb
<h1>New Association</h1>

<%= render 'form', association: @association %>

<%= link_to 'Back', associations_path %>

MemTest-rails/app/views/associations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @association.label %>
</p>

<p>
  <strong>Content:</strong>
  <%= @association.content %>
</p>

<%= link_to 'Edit', edit_association_path(@association) %> |
<%= link_to 'Back', associations_path %>

MemTest-rails/app/views/interactions/_form.html.erb
<%= form_for(interaction) do |f| %>
  <% if interaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(interaction.errors.count, "error") %> prohibited this interaction from being saved:</h2>

      <ul>
      <% interaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_id %>
    <%= f.text_field :question_id %>
  </div>

  <div class="field">
    <%= f.label :response %>
    <%= f.number_field :response %>
  </div>

  <div class="field">
    <%= f.label :prompt_time %>
    <%= f.datetime_select :prompt_time %>
  </div>

  <div class="field">
    <%= f.label :thinking_milis %>
    <%= f.number_field :thinking_milis %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MemTest-rails/app/views/interactions/edit.html.erb
<h1>Editing Interaction</h1>

<%= render 'form', interaction: @interaction %>

<%= link_to 'Show', @interaction %> |
<%= link_to 'Back', interactions_path %>

MemTest-rails/app/views/interactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interactions</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Response</th>
      <th>Prompt time</th>
      <th>Thinking milis</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interactions.each do |interaction| %>
      <tr>
        <td><%= interaction.question %></td>
        <td><%= interaction.response %></td>
        <td><%= interaction.prompt_time %></td>
        <td><%= interaction.thinking_milis %></td>
        <td><%= link_to 'Show', interaction %></td>
        <td><%= link_to 'Edit', edit_interaction_path(interaction) %></td>
        <td><%= link_to 'Destroy', interaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interaction', new_interaction_path %>

MemTest-rails/app/views/interactions/new.html.erb
<h1>New Interaction</h1>

<%= render 'form', interaction: @interaction %>

<%= link_to 'Back', interactions_path %>

MemTest-rails/app/views/interactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @interaction.question %>
</p>

<p>
  <strong>Response:</strong>
  <%= @interaction.response %>
</p>

<p>
  <strong>Prompt time:</strong>
  <%= @interaction.prompt_time %>
</p>

<p>
  <strong>Thinking milis:</strong>
  <%= @interaction.thinking_milis %>
</p>

<%= link_to 'Edit', edit_interaction_path(@interaction) %> |
<%= link_to 'Back', interactions_path %>

MemTest-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemTestRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

MemTest-rails/app/views/questions/_form.html.erb
<%= form_for(question) do |f| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :prompt %>
    <%= f.text_field :prompt %>
  </div>

  <div class="field">
    <%= f.label :choice1 %>
    <%= f.text_field :choice1 %>
  </div>

  <div class="field">
    <%= f.label :choice2 %>
    <%= f.text_field :choice2 %>
  </div>

  <div class="field">
    <%= f.label :choice3 %>
    <%= f.text_field :choice3 %>
  </div>

  <div class="field">
    <%= f.label :choice4 %>
    <%= f.text_field :choice4 %>
  </div>

  <div class="field">
    <%= f.label :correctIndex %>
    <%= f.number_field :correctIndex %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MemTest-rails/app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

MemTest-rails/app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Prompt</th>
      <th>Choice1</th>
      <th>Choice2</th>
      <th>Choice3</th>
      <th>Choice4</th>
      <th>Correctindex</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.prompt %></td>
        <td><%= question.choice1 %></td>
        <td><%= question.choice2 %></td>
        <td><%= question.choice3 %></td>
        <td><%= question.choice4 %></td>
        <td><%= question.correctIndex %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

MemTest-rails/app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

MemTest-rails/app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prompt:</strong>
  <%= @question.prompt %>
</p>

<p>
  <strong>Choice1:</strong>
  <%= @question.choice1 %>
</p>

<p>
  <strong>Choice2:</strong>
  <%= @question.choice2 %>
</p>

<p>
  <strong>Choice3:</strong>
  <%= @question.choice3 %>
</p>

<p>
  <strong>Choice4:</strong>
  <%= @question.choice4 %>
</p>

<p>
  <strong>Correctindex:</strong>
  <%= @question.correctIndex %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>